### PR TITLE
modularizing starter JS files, SCSS changes, and renaming bower file

### PR DESCRIPTION
**Pull request by pcsandford**
@rodrigopavezi I have made some additions to the way our starter files are set up to start building a base of more modular code. The main change is that main.js now references code in navigation.js and timeout.js where before we had to have all of this in one file which got messy on larger builds. Could you please review if it is ok to expose methods between files in this way? 

Please ignore the other changes and the commented out component-example.js, these are just to show an example and for reference. Thanks!

### CODE REVIEW

**Comment by rodrigopavezi** [comment]
@pcsandford looks good. One thing that I have seen is the behaviour of prefixing private attributes and methods of a js class with an underline `_`. That way it turns the code more readable and easy to spot what is private and what is not.  cheers

**Comment by rodrigopavezi** [comment]
@pcsandford one more thing that you can do is to instantiate a js class passing parameters like we have here in the widget https://github.com/Rise-Vision/widget-image/blob/master/src/widget/image.js#L120. This is incase you have a variable in main.js that is sharable between the module so you can pass this variable to the modules when instantiating them. I hope that helps. cheers

**Comment by rodrigopavezi** [comment]
@pcsandford another thing is to call classes camel case. That makes more readable. cheers

**Comment by pcsandford** [comment]
@rodrigopavezi thanks! So for example I would change `showPage` to `_showPage`? I was thinking of including parameters so that we could pass the the object and the target for a click event so I will add those in next.
 
In terms of the class naming do you mean in the CSS? We are basing the names on the BEM style of naming for Block__Element--Modifier style to try to make it consistent between Mat and myself when we work at the same time e.g. `page--home`, and `page__navigation--main` if that makes sense? Thanks!

**Comment by rodrigopavezi** [comment]
@pcsandford regarding the class name I meant the js objects like navigation and timeoutController. So they would be called Navigation and TimeoutController. I think it makes it more readable because when you look the code you can easily spot when a js class is being used. cheers

**Comment by pcsandford** [comment]
@rodrigopavezi ah awesome, that makes sense. I will change those up. Thanks!

**Comment by rodrigopavezi** [comment]
@pcsandford 👍 cheers

**Comment by pcsandford** [comment]
@rodrigopavezi I have made some changes to the names if you could please check if this is better. I tried to set up the methods with parameters but when I passed the arguments it looked like it was executing immediately. For example, I wanted `_showPage()` to accept targetButton and targetPage as params and when the function was called these would be `$(this)` and `$(this).attr('target')` but this wasn't working out. Thanks!

**Comment by rodrigopavezi** [comment]
@pcsandford looks good, just regarding the parameters I think it did not work because $(this) on main.js will refer to body element. I was curious and tried myself. It will only refer to the button when inside the function the on click event calls I believe. cheers

You know that is another way to create JS classes and import them using ES6. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes. As we are already using babel I think we can use classes and the [import](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/import) 

What do you think? cheers

**Comment by pcsandford** [comment]
@rodrigopavezi ah ok, that makes sense re $(this). I haven't used that es6 method before so I will definitely look into it and try it out. Thanks!

**Pull request merged**
