### PR TITLE
updating sass and script files

### PR DESCRIPTION
**Pull request by pcsandford**
@mmeiers please review - adding in more standard functions to the navigation file (which have already been reviewed by Donna) and updated the bower.json file to reference the new google sheet. I also added in some sass mixins and helper functions to size elements, as well as a framework for consistent z-index references and font weight references. 

Thanks!

### CODE REVIEW

**Comment by sheadarlison** [comment]
@pcsandford I know you said Donna reviewed some of this already but should this still be reviewed by Content?

**Comment by pcsandford** [comment]
@sheadarlison I don't think it is necessary this time - the functionality is taken from files they have already seen and stripped down to just the basics so we have a place to start from when we work on the next build, at which point we would be adding to what is here and then have them review again. So I think it makes more sense to have them review at that stage rather than now. Also, out of context it would be harder for them to review at this stage.

**Comment by sheadarlison** [comment]
@pcsandford Okay makes sense thanks!

**Comment by mmeiers** [comment]
@pcsandford 
Whats the moment js for in the bower file?

Also do you think we will be using the overlay rotation enough to include it in the main file or should we separate out?

👍

**Comment by pcsandford** [comment]
@mmeiers I was going to leave it in just in case, and rather than commenting it all out I just added the border around it so it is easily removed if not need -  I meant to explain that reasoning in the PR, sorry! If you don't think it is necessary tho I can take it out. 

I think that moment.js is now used by the new component so that's why it is listed in the bower file. Thanks!

**Pull request merged**
