### PR TITLE
Feature/cd test

### PR DESCRIPTION
**Pull request by mmeiers**
@pcsandford @rodrigopavezi I have implemented CD to this template build folder as a test. Please let me know if you see anything  wrong with the circle.yml or gulp file.

Thanks!

### CODE REVIEW

**Comment by mmeiers** [comment]
[[Improvement] Starter File [2]](https://trello.com/c/Ui9lQozl/3582-improvement-starter-file-2)

**Comment by rodrigopavezi** [comment]
@mmeiers sure, the circle.yml from the video is for when you have multiple projects such as a marketwall. The old circle.yml is for single project deployment so I would just revert the changes you did to circle.yml. I am not sure how it even passed. cheers

**Comment by rodrigopavezi** [comment]
@mmeiers nvm, I understood what happened here. You put the circle.yml outside on root of the repo. That will work fine. I found your file on storage. 

screen shot 2017-08-28 at 17 42 49

**Comment by rodrigopavezi** [comment]
@mmeiers looks good 👍  cheers

**Pull request merged**
